export const SELECCIONAR_CLIENTE = 'SELECCIONAR_CLIENTE';
export const SELECCIONAR_PRODUCTO = 'SELECCIONAR_PRODUCTO';
export const CANTIDAD_PRODUCTO = 'CANTIDAD_PRODUCTO';
export const DATOS_USUARIO = 'DATOS_USUARIO';
export const LISTA_INSUMOS = 'LISTA_INSUMOS';
export const LISTA_PRODUCTOS = 'LISTA_PRODUCTOS';